#!/bin/bash

ln -s /usr/share/8lan/8LAN.Core /usr/bin/8lan-core 
ln -s /usr/share/8lan/8LAN.GUI /usr/bin/8lan-gui

/bin/egrep  -i "^${USERID}" /etc/passwd
if [ $? -eq 0 ]; then
   echo "User $USERID exists, nothing to do..."
else
   useradd --home-dir /var/8lan 8lan
   mkdir -p /var/8lan
   chown 8lan:8lan /var/8lan
   sudo -u 8lan mkdir -p /var/8lan/share
   sudo -u 8lan mkdir -p /var/8lan/.8lan
   sudo -u 8lan echo "nick: \"$(hostname) (deamon)\"" >> /var/8lan/.8lan/core_settings.txt
   sudo -u 8lan echo "shared-folders: [/var/8lan/share]" >> /var/8lan/.8lan/core_settings.txt
   8lan-core -i 8lan
fi

